import { submitServerAction } from './action';
import { randomUUID } from 'node:crypto';
import { test, expect } from '@playwright/test';
import pg from 'pg';

test('T12 catalog creation, discarded cash draft and linked browser void survive reload', async ({ page, context, request }, testInfo) => {
  const data = await (await request.get('http://127.0.0.1:55994/__test/data')).json();
  expect((await context.request.post('http://127.0.0.1:55994/__test/login')).ok()).toBe(true);
  await context.addCookies([{ name: 'wetop_onboarding_later', value: '1', url: 'http://127.0.0.1:55993' }, { name: 'wetop_scope', value: encodeURIComponent(`business=${data.side.business};location=${data.side.location}`), url: 'http://127.0.0.1:55993' }]);
  const session = (await context.cookies()).find(cookie => cookie.name === 'wetop_session')!.value;
  const headers = { 'x-wetop-session': session, 'x-wetop-scope': `business=${data.side.business};location=${data.side.location}` };
  const api = async (path: string) => (await request.get(`http://127.0.0.1:55994/bar/${path}`, { headers })).json();
  for (const receipt of await api('receipts')) if (receipt.status === 'DRAFT') expect((await request.post(`http://127.0.0.1:55994/bar/receipts/${receipt.id}/post`, { headers, data: {} })).status()).toBe(201);
  const url = process.env.DATABASE_URL;
  if (!url || !['localhost','127.0.0.1'].includes(new URL(url).hostname)) throw new Error('Own localhost database required');
  const db = new pg.Client({ connectionString: url, options: '-c search_path=pms_test,public' });
  await db.connect();
  try {
    await page.goto('/bar');
    const name = `Synthetic browser category ${randomUUID()}`;
    const catalog = page.locator('.bar-catalogs section').filter({ has: page.getByRole('heading', { name: 'Категории', exact: true }) });
    await catalog.locator('[name="name"]').fill(name);
    await catalog.locator('[name="markup"]').fill('25');
    await submitServerAction(page, catalog.getByRole('button', { name: 'Добавить', exact: true }));
    await expect(catalog.getByText(`${name}, 25%`, { exact: true })).toBeVisible();
    await page.reload();
    await expect(catalog.getByText(`${name}, 25%`, { exact: true })).toBeVisible();
    expect((await api('categories')).filter((row: { name: string }) => row.name === name)).toHaveLength(1);
    await page.screenshot({ path: testInfo.outputPath('catalog-reloaded.png'), fullPage: true });
    const payment = await request.post(`http://127.0.0.1:55994/bar/receipts/${data.r1.id}/payments`, { headers, data: { amountMinor: '1234', method: 'CASH', idempotencyKey: randomUUID() } });
    expect(payment.status()).toBe(201);
    const saved = await payment.json();
    const cashId = (await db.query('SELECT cash_operation_id FROM bar_supplier_payments WHERE id=$1', [saved.id])).rows[0].cash_operation_id;
    const before = await api('report');
    const cashCount = async () => (await db.query('SELECT count(*)::int AS n FROM cash_operations WHERE property_id=$1', [data.side.property])).rows[0].n;
    const count = await cashCount();
    await page.goto('/finance#cash');
    await page.getByTestId('cash-expense-btn').click();
    const draft = page.getByTestId('cash-operation-form');
    await draft.getByTestId('cash-amount').fill('999');
    await draft.getByRole('button', { name: 'Отмена', exact: true }).click();
    await expect(draft).toHaveCount(0);
    await page.reload();
    await expect(page.getByTestId('cash-expense-btn')).toBeVisible();
    await expect(page.getByTestId('cash-operation-form')).toHaveCount(0);
    expect(await cashCount()).toBe(count);
    await page.screenshot({ path: testInfo.outputPath('cash-draft-discarded.png'), fullPage: true });
    await page.goto('/finance?src=cash#operations');
    const row = page.getByTestId('op-row').filter({ has: page.getByTestId('op-amount').filter({ hasText: '12,34' }) });
    await expect(row).toHaveCount(1);
    await row.getByTestId('cash-void').click();
    await submitServerAction(page, page.getByRole('dialog').getByRole('button', { name: 'Аннулировать', exact: true }));
    await expect(row.getByText('аннулирован', { exact: true })).toBeVisible();
    await expect(row).toHaveClass(/is-void/);
    await page.reload();
    await expect(row).toHaveCount(1);
    await expect(row.getByText('аннулирован', { exact: true })).toBeVisible();
    await expect(row).toHaveClass(/is-void/);
    expect((await db.query('SELECT status FROM cash_operations WHERE id=$1', [cashId])).rows[0].status).toBe('VOIDED');
    expect((await db.query('SELECT count(*)::int AS n FROM bar_supplier_payment_reversals WHERE payment_id=$1', [saved.id])).rows[0].n).toBe(1);
    const after = await api('report');
    expect(BigInt(after.supplierDebtMinor)).toBe(BigInt(before.supplierDebtMinor) + 1234n);
    expect(BigInt(after.supplierPaidMinor)).toBe(BigInt(before.supplierPaidMinor) - 1234n);
    expect(after.stockCostMinor).toBe(before.stockCostMinor);
    expect(await cashCount()).toBe(count);
    await page.screenshot({ path: testInfo.outputPath('supplier-void-reloaded.png'), fullPage: true });
  } finally { await db.end(); }
});
