import type { SVGProps } from 'react';
import {
  LogIn,
  LogOut,
  BedDouble,
  Check,
  Clock3,
  ChevronRight,
  ChevronLeft,
  LayoutDashboard,
  CalendarDays,
  Users,
  Tags,
  Wallet,
  Building2,
  Network,
  BookOpen,
  TriangleAlert,
  ChartNoAxesCombined,
  Search,
  Plus,
  ArrowRight,
  X,
  Menu,
  Settings2,
  Sun,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  CalendarCheck,
  ChevronDown,
  SlidersHorizontal,
  Ellipsis,
  ArrowUpRight,
  Monitor,
  Mail,
  Phone,
  Receipt,
  RefreshCw,
  Send,
  CreditCard,
  ShieldCheck,
  Brush,
  SprayCan,
  ClipboardCheck,
  MessagesSquare,
  CircleHelp,
} from 'lucide-react';
const icons = {
  arrival: LogIn,
  departure: LogOut,
  bed: BedDouble,
  check: Check,
  clock: Clock3,
  chevron: ChevronRight,
  back: ChevronLeft,
  today: LayoutDashboard,
  board: CalendarDays,
  guests: Users,
  rates: Tags,
  money: Wallet,
  inventory: Building2,
  channels: Network,
  journal: BookOpen,
  incidents: TriangleAlert,
  analytics: ChartNoAxesCombined,
  search: Search,
  plus: Plus,
  arrow: ArrowRight,
  close: X,
  menu: Menu,
  settings: Settings2,
  sun: Sun,
  moon: Moon,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  booking: CalendarCheck,
  down: ChevronDown,
  filter: SlidersHorizontal,
  more: Ellipsis,
  external: ArrowUpRight,
  system: Monitor,
  mail: Mail,
  phone: Phone,
  receipt: Receipt,
  refresh: RefreshCw,
  send: Send,
  card: CreditCard,
  shield: ShieldCheck,
  // уборка (DESIGN.md §7, «добавить при первом использовании»): грязно / убрано / проверено
  dirty: Brush,
  clean: SprayCan,
  inspected: ClipboardCheck,
  // переписка: раздел «ИИ-продавец» (DESIGN.md §7, «добавить при первом использовании»; ТЗ ред. 1 П6)
  chat: MessagesSquare,
  help: CircleHelp,
};
export type IconName = keyof typeof icons;
/** Все имена набора — для таблицы на странице /design-system (DESIGN.md §7). */
export const iconNames = Object.keys(icons) as IconName[];
export function Icon({ name, ...props }: SVGProps<SVGSVGElement> & { name: IconName }) {
  const Component = icons[name];
  return <Component width={20} height={20} strokeWidth={1.7} aria-hidden="true" {...props} />;
}
