import type { SVGProps } from 'react';
import {
  LogIn,
  LogOut,
  BedDouble,
  Check,
  Clock3,
  ChevronRight,
  LayoutDashboard,
  CalendarDays,
  Users,
  Tags,
  Wallet,
  Building2,
  Network,
  BookOpen,
  TriangleAlert,
  ChartNoAxesCombined,
  Search,
  Plus,
  ArrowRight,
  X,
  Menu,
  Settings2,
  Sun,
  Moon,
  Bell,
  Sparkles,
  PanelLeftClose,
  PanelLeftOpen,
  MessageSquare,
  CalendarCheck,
  ChevronDown,
  SlidersHorizontal,
  Ellipsis,
  ArrowUpRight,
  Monitor,
  Mail,
  Phone,
  Receipt,
  RefreshCw,
  Send,
  CreditCard,
  ShieldCheck,
} from 'lucide-react';
const icons = {
  arrival: LogIn,
  departure: LogOut,
  bed: BedDouble,
  check: Check,
  clock: Clock3,
  chevron: ChevronRight,
  today: LayoutDashboard,
  board: CalendarDays,
  guests: Users,
  rates: Tags,
  money: Wallet,
  inventory: Building2,
  channels: Network,
  journal: BookOpen,
  incidents: TriangleAlert,
  analytics: ChartNoAxesCombined,
  search: Search,
  plus: Plus,
  arrow: ArrowRight,
  close: X,
  menu: Menu,
  settings: Settings2,
  sun: Sun,
  moon: Moon,
  bell: Bell,
  ai: Sparkles,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  messages: MessageSquare,
  booking: CalendarCheck,
  down: ChevronDown,
  filter: SlidersHorizontal,
  more: Ellipsis,
  external: ArrowUpRight,
  system: Monitor,
  mail: Mail,
  phone: Phone,
  receipt: Receipt,
  refresh: RefreshCw,
  send: Send,
  card: CreditCard,
  shield: ShieldCheck,
};
export type IconName = keyof typeof icons;
export function Icon({ name, ...props }: SVGProps<SVGSVGElement> & { name: IconName }) {
  const Component = icons[name];
  return <Component width={20} height={20} strokeWidth={1.7} aria-hidden="true" {...props} />;
}
